### ISSUE TITLE
Frquent Pop-up - operation taking longer than expected

### ISSUE THREAD

**Issue by dnikkel** [yoichiro/chromeos-filesystem-webdav#11]
I've just been using the WEBDAV plug-in for a few days.  So far, just to stream music from my Synology NAS.  The first time I used it, it seemed to be working perfectly, streaming music for at least an hour without a noticeable hiccup.  However, I was getting a frequent pop-up with a message, "An operation is taking longer than expected.  Do you wish to abort it?"  I would just click on the "X" to dismiss, not the abort label and streaming seemed to continue with no impact. There was never any sort of detectable interruption of the music.

Today, however, I am still getting the pop-up, but music is also freezing at the same time that the pop-up appears.  I can't get the music to resume without restarting the track.

I am running on a Chromebox with a wired 1GB connection, so there should not be network issues.  Chrome OS version is 41 and WebDAV version is 1.0.1.  My Synology NAS is running DSM 5.1.  Let me know if you need further details.

**Comment by yoichiro** [comment]
@dnikkel If you face this issue at the next time, could you check the console log by the following steps?

https://github.com/yoichiro/chromeos-filesystem-webdav/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by dnikkel** [comment]
Interesting, I've had the problem on several more occasions - both with the notification being presented but no noticeable interruption and also with streaming actually halting.  In either case, nothing is being logged to the console, either at the point the dialog is presented, or when I dismiss it.  In either scenario, all I see being logged is the normal stream of file open followed by reads.

**Comment by dnikkel** [comment]
OK, today I've had music playback freeze up a couple times and I am seeing this error logged in the console:

Unchecked runtime.lastError while running fileSystemProviderInternal.readFileRequestedSuccess: NOT_FOUND
    at null.<anonymous> (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:691:17)
    at null.<anonymous> (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:250:21)
    at j (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:2:27295)
    at Object.k.fireWith [as resolveWith](chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:2:28108)
    at x (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:4:22080)
    at XMLHttpRequest.<anonymous> (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:458:29)

Same experience I've had in the past - I can't get playback to continue without restarting the track.

**Comment by supercooltough** [comment]
@dnikkel have you found a resolution? I see the same notification

**Comment by dnikkel** [comment]
I'm afraid not.  I only used WEBDAV to access to local NAS until SMB became available and then switched to that.  The SMB driver seems to have similar issues, at least intermittently.  I don't use it very often any more.
