### ISSUE TITLE
ownCloud: operation is taking longer than expected

### ISSUE THREAD

**Issue by nealey** [yoichiro/chromeos-filesystem-webdav#31]
I am unable to open any file mounted on my ownCloud server: it always presents a popup saying "The operation is taking langer than expected". This includes generating thumbnails when using the Files app in grid mode.

I have verified that other users of the server are able to use webDAV successfully. It appears to submit a PROPFIND successfully, getting a 207 back. I am happy to run local debugging if instructed.

Here are relevant server logs:

```
172.20.0.2 - neale [18/Sep/2017:15:56:11 +0000] "PROPFIND /remote.php/webdav HTTP/1.0" 207 1157 "-" "Mozilla/5.0 (X11; CrOS x86_64 9592.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.114 Safari/537.36"
172.20.0.2 - neale [18/Sep/2017:15:56:11 +0000] "PROPFIND /remote.php/webdav/Art/ir-pyramid.svg HTTP/1.0" 207 1138 "-" "Mozilla/5.0 (X11; CrOS x86_64 9592.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.114 Safari/537.36"
172.20.0.2 - neale [18/Sep/2017:15:56:12 +0000] "PROPFIND /remote.php/webdav/Art/ir-pyramid.svg HTTP/1.0" 207 1138 "-" "Mozilla/5.0 (X11; CrOS x86_64 9592.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.114 Safari/537.36"
172.20.0.2 - neale [18/Sep/2017:15:56:12 +0000] "PROPFIND /remote.php/webdav/Art/ir-pyramid.svg HTTP/1.0" 207 1138 "-" "Mozilla/5.0 (X11; CrOS x86_64 9592.94.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.114 Safari/537.36"
```

**Comment by nealey** [comment]
I have just found your page about console logging the background page. It appears to be referencing an undefined variable:

```
10:09:40.921 background.js:133 rootPath: /remote.php/webdav
10:09:40.923 background.js:668 onGetMetadataRequested: thumbnail=false
10:09:40.924 background.js:669 {entryPath: "/Art/ir-pyramid.svg", fileSystemId: "webdavfs://neale/http://cfl-owncloud/remote.php/webdav", isDirectory: false, mimeType: true, modificationTime: false, …}
10:09:40.926 background.js:1103 getMetadataCache: Created. webdavfs://neale/http://cfl-owncloud/remote.php/webdav
10:09:40.970 background.js:679 {metadata: {…}}
10:09:40.971 _generated_background_page.html:1 IsDirectory specified, but not requested.
10:09:40.971 _generated_background_page.html:1 Name specified, but not requested.
10:09:40.971 _generated_background_page.html:1 Size specified, but not requested.
10:09:40.971 _generated_background_page.html:1 Last modification time specified, but not requested.
10:09:40.973 background.js:668 onGetMetadataRequested: thumbnail=false
10:09:40.974 background.js:669 {entryPath: "/Art/ir-pyramid.svg", fileSystemId: "webdavfs://neale/http://cfl-owncloud/remote.php/webdav", isDirectory: true, mimeType: false, modificationTime: false, …}
10:09:41.012 background.js:679 {metadata: {…}}
10:09:41.012 _generated_background_page.html:1 Name specified, but not requested.
10:09:41.012 _generated_background_page.html:1 Last modification time specified, but not requested.
10:09:41.012 _generated_background_page.html:1 MIME type specified, but not requested.
10:09:41.015 background.js:695 onOpenFileRequested
10:09:41.017 background.js:696 {filePath: "/Art/ir-pyramid.svg", fileSystemId: "webdavfs://neale/http://cfl-owncloud/remote.php/webdav", mode: "READ", requestId: 234}
10:09:41.021 background.js:668 onGetMetadataRequested: thumbnail=false
10:09:41.023 background.js:669 {entryPath: "/Art/ir-pyramid.svg", fileSystemId: "webdavfs://neale/http://cfl-owncloud/remote.php/webdav", isDirectory: false, mimeType: false, modificationTime: true, …}
10:09:41.068 background.js:679 {metadata: {…}}
10:09:41.071 _generated_background_page.html:1 IsDirectory specified, but not requested.
10:09:41.071 _generated_background_page.html:1 Name specified, but not requested.
10:09:41.071 _generated_background_page.html:1 MIME type specified, but not requested.
10:09:41.072 background.js:706 onReadFileRequested - start
10:09:41.073 background.js:707 {fileSystemId: "webdavfs://neale/http://cfl-owncloud/remote.php/webdav", length: 113311, offset: 0, openRequestId: 234, requestId: 236}
10:09:41.074 _generated_background_page.html:1 Error in event handler for fileSystemProvider.onReadFileRequested: ReferenceError: metadataCache is not defined
    at WebDavFS.onReadFileRequested (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:710:35)
    at WebDavFS.<anonymous> (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:1048:22)
    at WebDavFS.<anonymous> (chrome-extension://hmckflbfniicjijmdoffagjkpnjgbieh/background.js:1013:17)
```

**Comment by bhill74** [comment]
I am having the same problem. I will attach a screen shot, but they appear to be the same errors.
![screenshot 2017-11-16 at 4 16 01 pm](https://user-images.githubusercontent.com/24836863/32916827-3a36d6dc-caeb-11e7-983f-8e59163ee9e0.png)

**Comment by bhill74** [comment]
I should also point out that this is only for reading files from the webdav, writing files seems to work no problem (so far).

**Comment by lggregorio** [comment]
Same problem here, whenever I open Webdav to access my ownCloud server I get the message that it is taking too long to complete. All is true to open folders, copy files to local drive or even upload.
![screenshot 2017-12-31 at 10 03 12](https://user-images.githubusercontent.com/29231852/34461463-fd8f3734-ee11-11e7-8b6b-7f0349362233.png)
